services:
  - type: web
    name: stock-pulse
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 2 --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
    plan: free
